###服务端口号
server:
  port: 8011
spring:
  application:
    name: order
###eureka 基本信息配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

