###服务端口号
server:
  port: 8010
spring:
  application:
    name: vip
###eureka 基本信息配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka,http://localhost:8101/eureka,http://localhost:8102/eureka

